### ISSUE TITLE
Anomalies in scripts

### ISSUE THREAD

**Issue by intrinicity** [RideLikeTheWind/tga-ws-php#1]
Hi. 
1. require('soap_ws_sec.php'); on line 3 is not included in the package. Assuming the intent was to replace it with WSSecurity.php? If done so, then ...
2. Undefined variable: header in ../includes/tga-ws-php-master/ws-access.php on line 21.

Wondering if this piece of work is being maintained and indeed if all the files match.

Dave

**Comment by RideLikeTheWind** [comment]
@intrinicity sorry - I wasn't maintaining the code. I'll have a look at the issue for you. 

Cheers!

**Comment by RideLikeTheWind** [comment]
Fixed - it was a require issue expecting the wrong file. I have also looked at the undefined variable issue. I think it is called with the $client->generateWSSecurityHeader(); Reading through it looks like it should work. Let me know if it doesn't and I will try and clone the repo of the original code and check it out for you. Cheers!
