### ISSUE TITLE
TGA Webservices examples

### ISSUE THREAD

**Issue by ufairiya** [RideLikeTheWind/tga-ws-php#2]
Hi, thank you for the startup code to access the tga webservices.
As you have noted, I can find only java, dotnet sdk in their website.
However those also are lacking in any real meaningful examples implementing atleast some key webservice calls. I can find only a call to GetServerTime implemented in it. Is there any detailed documentation or examples/ codes available to go over ? Can you help in this regard ? 
I am going to develop some customized external systems to consume the webservice which will help students to have a better preparation before going to the class. It is yet to be conceived in full but your insights on the usage of the webservice will provide us a better start. Thanks in advance. Subash.

**Comment by RideLikeTheWind** [comment]
Hi Subash,

The calls to the webservice are rubbish, to be honest. Essentially, you make a call to the service and it pulls down an XML document, which has no consistent tree between documents, so you end up trawling the entire document to find the data. The PHP framework I wrote worked on the previous iteration, though it should be fine with the current. We were pushing for a more usable dataset, like JSON, but I doubt they will listen (you have seen the listing on data.gov.au). 

Good luck - I wish I could be of more help. 

Joe
